name: Hello World
on:
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Dí hola
        run: echo "Monse Castañon"

  first_task1:
    runs-on: ubuntu-latest

    steps:
      - name: Saluda a todos
        run: echo "Welcome a todos"

      - name: FechaSistema
        run: 
          echo "Bienvenidos a primer desafío" 
          echo "Donde fue creado mi primer Workflow" 
          echo "Gracias a Dios" 
          echo "El día" 
          date
        
      
